BudgetBundle\Entity\Category:
    type: entity
    repositoryClass: BudgetBundle\Repository\CategoryRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        color:
            type: string
            length: 255
            unique: true
        type:
            type: string
            length: 255
    oneToMany:
        operations:
            targetEntity: BudgetBundle\Entity\Operation
            mappedBy: category
        children:
            targetEntity: BudgetBundle\Entity\Category
            mappedBy: parent
    manyToOne:
        parent:
          targetEntity: BudgetBundle\Entity\Category
          inversedBy: children
    lifecycleCallbacks: {  }
