BudgetBundle\Entity\Operation:
    type: entity
    repositoryClass: BudgetBundle\Repository\OperationRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        label:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
        amount:
            type: float
        signature:
            type: string
            length: 255
            unique: true
        importDate:
            type: datetime
        manual:
            type: boolean
            options:
                default: false
    manyToOne:
        account:
            targetEntity: BudgetBundle\Entity\Account
            inversedBy: operations
            joinColumn:
                name: account_id
                referencedColumnName: id
        category:
            targetEntity: BudgetBundle\Entity\Category
            inversedBy: operations
            joinColumn:
                name: category_id
                referencedColumnName: id
    oneToOne:
        reconciliation:
            targetEntity: BudgetBundle\Entity\Operation
            inversedBy: reconcialiated
            joinColumn:
                name: operation_id
                referencedColumnName: id
        reconcialiated:
            targetEntity: BudgetBundle\Entity\Operation
            mappedBy: reconciliation
    lifecycleCallbacks:
        prePersist: [ setSignature ]
