BudgetBundle\Entity\OperationPattern:
    type: entity
    repositoryClass: BudgetBundle\Repository\OperationPatternRepository
    table: null
    indexes:
        pattern_index:
          columns: [ pattern ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pattern:
            type: string
            length: 255
            unique: true
        description:
            type: string
            length: 255
            nullable: true
    manyToOne:
        category:
            targetEntity: BudgetBundle\Entity\Category
            inversedBy: operations
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: {  }
