<?php
/**
 * Copyright (c) Nicolas Grancher <https://github.com/nicolasgrancher> 2017.
 */

namespace BudgetBundle\Repository;

/**
 * MonitoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @package BudgetBundle\Repository
 */
class MonitoringRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findMonthlyCostByMonitoring()
    {
        return $this->createQueryBuilder('m')
            ->select('m.name AS name,
            SUM(o.amount) AS amount,
            MIN(o.date) AS beginningDate,
            MAX(o.date) AS endingDate')
            ->join('m.categories', 'c')
            ->join('c.operations', 'o')
            ->where('o.date >= m.beginningDate')
            ->groupBy('m')
            ->getQuery()
            ->getArrayResult();
    }
}
