<?php
/**
 * Copyright (c) Nicolas Grancher <https://github.com/nicolasgrancher> 2017.
 */

namespace BudgetBundle\Repository;

use BudgetBundle\Entity\Account;

/**
 * Class OperationRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @package BudgetBundle\Repository
 */
class OperationRepository extends \Doctrine\ORM\EntityRepository
{
    const CATEGORY_SAVING = 6;

    public function findAmountByMonth()
    {
        $results = $this->createQueryBuilder('o')
            ->select('SUBSTRING(o.date, 1, 4) AS year, 
            SUBSTRING(o.date, 6, 2) AS month, 
            SUM(o.amount) AS amount')
            ->groupBy('year, month')
            ->where('o.category != :savingCategory')
            ->andWhere('o.reconciliation IS NULL')
            ->setParameter('savingCategory', static::CATEGORY_SAVING)
            ->getQuery()
            ->getArrayResult();

        $operations = [];

        foreach ($results as $result) {
            $operations[$result['year'] . '-' . $result['month']] = [
                'year' => $result['year'],
                'month' => $result['month'],
                'amount' => $result['amount'],
            ];
        }

        return $operations;
    }

    /**
     * Find amount of manually added operations with no reconciliation
     *
     * @param Account $account
     * @return array
     */
    public function findAmountManuallyAdded(Account $account)
    {
        return $this->createQueryBuilder('o')
            ->select('SUM(o.amount) AS amount')
            ->where('o.account = :account')
            ->andWhere('o.manual = true')
            ->andWhere('o.reconciliation IS NULL')
            ->setParameter('account', $account)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
