<?php
/**
 * Copyright (c) Nicolas Grancher <https://github.com/nicolasgrancher> 2017.
 */

namespace BudgetBundle\Repository;

/**
 * Class OperationPatternRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @package BudgetBundle\Repository
 */
class OperationPatternRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPattern($match)
    {
        return $this->createQueryBuilder('op')
            ->where("REGEXP(:match, op.pattern) = true")
            ->setParameter('match', $match)
            ->getQuery()
            ->getResult();
    }
}
