<?php
/**
 * Copyright (c) Nicolas Grancher <https://github.com/nicolasgrancher> 2017.
 */

namespace BudgetBundle\Repository;

/**
 * Class OperationRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @package BudgetBundle\Repository
 */
class OperationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAmountByMonth()
    {
        $results = $this->createQueryBuilder('o')
            ->select('SUBSTRING(o.date, 1, 4) AS year, 
            SUBSTRING(o.date, 6, 2) AS month, 
            SUM(o.amount) AS amount')
            ->groupBy('year, month')
            ->getQuery()
            ->getArrayResult();

        $operations = [];

        foreach ($results as $result) {
            $operations[$result['year'] . '-' . $result['month']] = [
                'year' => $result['year'],
                'month' => $result['month'],
                'amount' => $result['amount'],
            ];
        }

        return $operations;
    }
}
